[versions]
pluginYmlPaper = "0.9.0"
paperApi = "26.2.build.+"
velocityApi = "3.5.0-SNAPSHOT"
floodgataApi = "2.2.3-SNAPSHOT"
placeholderApi = "2.12.3"
vivecraftVelocityExtensions = "1.1"
shadow = "9.5.1"

[libraries]
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi" }
velocityApi = { group = "com.velocitypowered", name = "velocity-api", version.ref="velocityApi" }
floodgateApi = { group = "org.geysermc.floodgate", name = "api", version.ref="floodgataApi" }
placeholderApi = { group = "me.clip", name = "placeholderapi", version.ref="placeholderApi" }
vivecraftVelocityExtensions = { group = "uk.co.notnull", name = "VivecraftVelocityExtensions", version.ref="vivecraftVelocityExtensions" }

[plugins]
pluginYmlPaper = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYmlPaper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }