name: PlatformDetection
version: @project.version@
main: uk.co.notnull.platformdetection.PlatformDetectionPaper
author: Jim (AnEnragedPigeon)
api-version: '1.21'
load: STARTUP
description: Detects the platform/mod players are using

dependencies:
  server:
    PlaceholderAPI:
      load: AFTER
      required: false
    floodgate:
      load: AFTER
      required: false
    Vivecraft-Spigot-Extensions:
      load: AFTER
      required: false
